SET SQL_SAFE_UPDATES=0;
Delete from `NFLMODEL`.`USER`;

DELETE FROM `NFLMODEL`.`USER_STATUS` WHERE UID is not null ;
INSERT INTO `NFLMODEL`.`USER_STATUS` (`CODE`, `LABEL`) VALUES ('ACTIVE', 'Active');
INSERT INTO `NFLMODEL`.`USER_STATUS` (`CODE`, `LABEL`) VALUES ('INACTIVE', 'Inactive');
INSERT INTO `NFLMODEL`.`USER_STATUS` (`CODE`, `LABEL`) VALUES ('BANNED', 'Banned');

DELETE FROM  `NFLMODEL`.`USER_TYPE` WHERE UID is not null ;
INSERT INTO `NFLMODEL`.`USER_TYPE` (`CODE`, `LABEL`) VALUES ('HUMAN', 'Human');
INSERT INTO `NFLMODEL`.`USER_TYPE` (`CODE`, `LABEL`) VALUES ('ROBOT', 'Computer');
commit;

SET SQL_SAFE_UPDATES=0;

Delete from `NFLMODEL`.`USER` where type = (Select UID from `NFLMODEL`.`USER_TYPE` WHERE CODE = 'ROBOT') ;
INSERT INTO `NFLMODEL`.`USER` (`USER_UID`,`NAME`,`PWD`,`STATUS`,`TYPE`) VALUES
('ROBOT', 'COMPUTER','1234', (select UID from `NFLMODEL`.`USER_STATUS` WHERE CODE = 'ACTIVE'),(Select UID from `NFLMODEL`.`USER_TYPE` WHERE CODE = 'ROBOT') );

INSERT INTO `NFLMODEL`.`USER` (`USER_UID`,`NAME`,`STATUS`,`TYPE`) VALUES
('USER_ADMIN', 'ADMIN_USER', (select UID from `NFLMODEL`.`USER_STATUS` WHERE CODE = 'ACTIVE'),(Select UID from `NFLMODEL`.`USER_TYPE` WHERE CODE = 'HUMAN') );
SELECT * FROM `NFLMODEL`.`USER`;


SET SQL_SAFE_UPDATES=0;
Delete from `NFLMODEL`.`POSITION_PRM`;
INSERT INTO `NFLMODEL`.`POSITION_PRM` (`CODE`, `LABEL`) VALUES ('LINEBACKERS',   'Linebackers ');
INSERT INTO `NFLMODEL`.`POSITION_PRM` (`CODE`, `LABEL`) VALUES ('CORNERBACKS',   'Cornerbacks ');
INSERT INTO `NFLMODEL`.`POSITION_PRM` (`CODE`, `LABEL`) VALUES ('NICKELBACKS',   'Nickelbacks ');
INSERT INTO `NFLMODEL`.`POSITION_PRM` (`CODE`, `LABEL`) VALUES ('SAFETIES',      'Safeties ');
INSERT INTO `NFLMODEL`.`POSITION_PRM` (`CODE`, `LABEL`) VALUES ('QUARTERBACK',   'Quarterback ');
INSERT INTO `NFLMODEL`.`POSITION_PRM` (`CODE`, `LABEL`) VALUES ('RUNNING_BACKS', 'Running Backs');
INSERT INTO `NFLMODEL`.`POSITION_PRM` (`CODE`, `LABEL`) VALUES ('LINEBACKERS',   'Linebackers ');
INSERT INTO `NFLMODEL`.`POSITION_PRM` (`CODE`, `LABEL`) VALUES ('CORNERBACKS',   'Cornerbacks ');
INSERT INTO `NFLMODEL`.`POSITION_PRM` (`CODE`, `LABEL`) VALUES ('NICKELBACKS',   'Nickelbacks ');
 
 

 